In [1]:
my_list = [1, 2, 3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### CREATING NUMPY ARRAY

In [12]:
# similar to pythons' range() function
# (start, stop, step size)

np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [14]:
# ((num of rows, num of cols))
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
# linspace != arange
# (start, stop, number of evenly spaced points from start to stop)
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### IDENTITY MATRIX

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
# rand -> returns random samples of uniform distributin

np.random.rand(5)

array([0.04364778, 0.74184885, 0.30185807, 0.01687344, 0.73723382])

In [21]:
np.random.rand(5, 5)

array([[0.88395768, 0.24960927, 0.46605823, 0.89585859, 0.56021627],
       [0.87516246, 0.08307671, 0.66627741, 0.63264324, 0.95516695],
       [0.09351491, 0.78640751, 0.56774663, 0.35159688, 0.71228271],
       [0.68586711, 0.32472467, 0.41232568, 0.68433858, 0.30153107],
       [0.96337155, 0.54118692, 0.37858013, 0.82528844, 0.97455631]])

In [22]:
# standard normal distribution

np.random.randn(2)

array([0.67527953, 1.31726652])

In [23]:
np.random.rand(4, 4)

array([[0.48636779, 0.76265936, 0.47397465, 0.80716984],
       [0.36624478, 0.05696901, 0.47891222, 0.4006973 ],
       [0.83612652, 0.74134854, 0.01518462, 0.95211369],
       [0.39016931, 0.48937165, 0.52430221, 0.42888428]])

In [24]:
np.random.randint(1, 100)

61

In [25]:
np.random.randint(1, 100, 10)

array([36, 48, 93, 36, 14, 10, 95, 27, 44, 12])

In [26]:
arr = np.arange(25)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [27]:
ranarr = np.random.randint(0, 50, 10)

In [28]:
ranarr

array([25, 29,  8,  9, 47, 11, 35, 40, 12, 26])

#### RESHAPE METHOD

In [29]:
# we pass new dimensions
# we get error if we can't fill the new array completely
# num_row * num_cols = num_elements

arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
ranarr

array([25, 29,  8,  9, 47, 11, 35, 40, 12, 26])

In [31]:
ranarr.max()

47

In [32]:
ranarr.min()

8

In [33]:
# get index value of the max value (or min value)

ranarr.argmax()

4

In [34]:
ranarr.argmin()

2

In [35]:
arr.shape

(25,)

In [37]:
arr = arr.reshape(5, 5)

In [38]:
arr.shape

(5, 5)

In [39]:
arr.dtype

dtype('int64')

In [40]:
from numpy.random import randint

randint(2, 10)

5